swagger: "2.0"
info:
  title: training-memo-api
  description: "API used for personal training record"
  version: "1.0.0"
schemes:
  - "https"
produces:
  - application/json
x-google-backend:
  address: https://asia-northeast1-earnest-math-313901.cloudfunctions.net/training_memo
x-google-endpoints:
  - name: asia-northeast1-earnest-math-313901.cloudfunctions.net
    allowCors: true
paths:
  "/daily_record":
    options:
      description: "Enable CORS by returning the correct headers"
      operationId: "CORS_support"
      responses:
        "204":
          description: "No content"
          headers:
            Access-Control-Allow-Origin:
              type: string
              description: "CORS origin"
            Access-Control-Allow-Methods:
              type: string
              description: "CORS methods"
            Access-Control-Allow-Headers:
              type: string
              description: "CORS headers"
    get:
      description: Get daily records
      operationId: get_daily_record
      responses:
        "200":
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              data:
                type: array
                items:
                  $ref: "#/definitions/get_daily_record_response_data"
        "404":
          description: The request body invalid or missing.
    post:
      description: Create or update daily record
      operationId: post_daily_record
      parameters:
        - in: body
          name: request_body
          required: true
          schema:
            $ref: "#/definitions/daily_record"
      responses:
        "200":
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              id:
                type: string
        "404":
          description: The request body invalid or missing.
    delete:
      description: Delete daily record
      operationId: delete_daily_record
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Document id of Firestore
      responses:
        "200":
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
  "/menu":
    get:
      description: Get menu
      operationId: get_menu
      responses:
        "200":
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              data:
                type: array
                items:
                  $ref: "#/definitions/get_menu_response_data"
        "404":
          description: The request body invalid or missing.
    post:
      description: Create or update training menu
      operationId: menu
      parameters:
        - in: body
          name: request_body
          required: true
          schema:
            $ref: "#/definitions/menu"
      responses:
        "200":
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              id:
                type: string
        "404":
          description: The request body invalid or missing.
    delete:
      description: Delete training menu
      operationId: delete_menu
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Document id of Firestore
      responses:
        "200":
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
definitions:
  get_daily_record_response_data:
    type: object
    properties:
      id:
        type: string
      count:
        type: integer
      menu_id:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  get_menu_response_data:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      unit:
        type: string
      weekly_quota:
        type: integer
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  daily_record:
    type: object
    properties:
      menu:
        type: string
      count:
        type: integer
      date:
        type: string
    required:
      - menu
      - count
  menu:
    type: object
    properties:
      name:
        type: string
      unit:
        type: string
      weekly_quota:
        type: integer
