name: Deploy Cloud Functions
on:
  # mainへのPush時、または手動でワークフローを実行する
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  job_id:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/466155598212/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions@earnest-math-313901.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "training_memo"
          runtime: "python312"
          env_vars: FIRESTORE_ROOT_COLLECTION=training_memo, FIRESTORE_ROOT_DOCUMENT=v1
          source_dir: "cloud_functions"
